[package]
name = "storage"
version = "0.1.0"
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "storage"
path = "src/lib.rs"

[dependencies]
soroban-sdk = { workspace = true }
