name: "Crowdfund challenge validation"

on:
  pull_request:
    branches:
      - main

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Install axios library
        run: npm install axios

      - name: Validate crowdfund challenge
        run: node crowdfund/validate-challenge.js

      # - name: Install Github CLI to auto-close PR
      #   uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      # - name: Make repository dir a safe directory to allow the worker to close the PR and delete the branch
      #   run: git config --system --add safe.directory /__w/soroban-dapps-challenge/soroban-dapps-challenge

      # - name: Close Pull Request and delete the remote branch
      #   run: gh pr close ${{ github.event.pull_request.number }}
      #       --comment "Auto-closing PR as verification completed"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
